"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PySelfControl.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': False, 'includes': ['sys','os','time','threading','PySide.QtCore', 'PySide.QtGui']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
