name: Test Only

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # - uses: actions/cache@v1
      #   with:
      #     path: vendor/bundle
      #     key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gem-

      # - uses: actions/cache@v1
      #   with:
      #     path: Pods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-

      - name: Install gems
        run: |
          # bundle config path vendor/bundle
          # bundle config set without 'default doc job cable storage ujs test db'
          bundle install --jobs 4 --retry 3

      - name: Install Dependences
        run: |
          bundle exec pod update
          bundle exec pod install

      - name: Clean and Build
        run: |
          bundle exec xcodebuild \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -workspace SelfControl.xcworkspace \
            -scheme "SelfControl" \
            -configuration Release \
            clean build

      # v2
      # - name: Install Dependences
      #   run: |
      #     sudo gem install cocoapods cocoapods-prune-localizations
      #     pod setup
      #     pod update
      #     pod install

      # - name: Clean and Build
      #   run: |
      #     xcodebuild \
      #       CODE_SIGN_IDENTITY="" \
      #       CODE_SIGNING_REQUIRED=NO \
      #       -workspace SelfControl.xcworkspace \
      #       -scheme "SelfControl" \
      #       -configuration Release \
      #       clean build

      # - name: Build
      #   uses: sersoft-gmbh/xcodebuild-action@v1.4
      #   with:
      #     project: SelfControl.xcodeproj
      #     scheme: SelfControl
      #     destination: platform=macOS
      #     action: build

      # # https://github.com/mxcl/xcodebuild
      # - name: Build
      #   uses: mxcl/xcodebuild@v1
      #   with:
      #     xcode: ^12
      #     platform: macOS
      #     action: build
      #     code-coverage: false
      #     configuration: release
